title: TECH Setu
email: info@techsetu.org
description: >-
  A student-led non-profit initiative working on bridging the gap between IT Students and IT Industry
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://techsetu.org"
# image_base_url: /assets/img
image_base_url: https://techsetu.sirv.com/img
thumbnail: thumbnail.jpg

twitter_username: '@tech_setu'
google_analytics: G-6YGR4H8C5L

permalink: /blogs/:year/:month/:day/:title/

# Build settings
markdown: kramdown
